import { createGlobalTheme, createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    canvas: null,
    surface: null,
    surfaceSubtle: null,
    border: null,
    borderPrimary: null,
    textPrimary: null,
    textSecondary: null,
    textInverse: null,
    navigation: null,
    navigationSurface: null,
    navigationBorder: null,
    navigationText: null,
    navigationTextSecondary: null,
    navigationAccent: null,
    brand: null,
    brandHover: null,
    success: null,
    successSubtle: null,
    warning: null,
    warningSubtle: null,
    danger: null,
    dangerSubtle: null,
    infoSubtle: null,
  },
  font: {
    family: null,
    familyDisplay: null,
    familyMono: null,
    weight: {
      regular: null,
      medium: null,
      semibold: null,
      bold: null,
    },
    size: {
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      display: null,
    },
    lineHeight: {
      tight: null,
      normal: null,
      relaxed: null,
    },
    letterSpacing: {
      tight: null,
      normal: null,
    },
  },
  space: {
    1: null,
    2: null,
    3: null,
    4: null,
    6: null,
    8: null,
    10: null,
    12: null,
  },
  radius: {
    sm: null,
    md: null,
    lg: null,
    full: null,
  },
  shadow: {
    sm: null,
    md: null,
  },
  transition: {
    fast: null,
  },
  height: {
    gnb: null,
  },
  width: {
    navigation: null,
  },
}, (_value, path) => path.join("-").replace(/^space-/, "spacing-"));

createGlobalTheme(":root", vars, {
  color: {
    canvas: "#171717",
    surface: "#1f1f1f",
    surfaceSubtle: "#292929",
    border: "#333333",
    borderPrimary: "#606060",
    textPrimary: "#ededed",
    textSecondary: "#a3a3a3",
    textInverse: "#102b1e",
    navigation: "#171717",
    navigationSurface: "#232323",
    navigationBorder: "#333333",
    navigationText: "#d4d4d4",
    navigationTextSecondary: "#a3a3a3",
    navigationAccent: "#3ecf8e",
    brand: "#3ecf8e",
    brandHover: "#65dba5",
    success: "#65dba5",
    successSubtle: "#19372a",
    warning: "#f5c76b",
    warningSubtle: "#382d1b",
    danger: "#ff9b9b",
    dangerSubtle: "#3d2323",
    infoSubtle: "#19372a",
  },
  font: {
    family:
      "var(--font-inter), Pretendard, Apple SD Gothic Neo, system-ui, sans-serif",
    familyDisplay:
      "var(--font-inter), Pretendard, Apple SD Gothic Neo, system-ui, sans-serif",
    familyMono: "SFMono-Regular, Consolas, Liberation Mono, monospace",
    weight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    size: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.25rem",
      xl: "1.5rem",
      display: "2rem",
    },
    lineHeight: {
      tight: "1.2",
      normal: "1.5",
      relaxed: "1.7",
    },
    letterSpacing: {
      tight: "-0.02em",
      normal: "0",
    },
  },
  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
  },
  radius: {
    sm: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    full: "999px",
  },
  shadow: {
    sm: "0 1px 2px rgb(0 0 0 / 0.16)",
    md: "0 12px 32px rgb(0 0 0 / 0.32)",
  },
  transition: {
    fast: "160ms ease",
  },
  height: {
    gnb: "56px",
  },
  width: {
    navigation: "248px",
  },
});
