import { createGlobalTheme, createGlobalThemeContract } from "@vanilla-extract/css";

export const vars = createGlobalThemeContract({
  color: {
    canvas: null,
    surface: null,
    surfaceSubtle: null,
    border: null,
    borderPrimary: null,
    textPrimary: null,
    textSecondary: null,
    textInverse: null,
    navigation: null,
    navigationSurface: null,
    navigationBorder: null,
    navigationText: null,
    navigationTextSecondary: null,
    navigationAccent: null,
    brand: null,
    brandHover: null,
    success: null,
    successSubtle: null,
    warning: null,
    warningSubtle: null,
    danger: null,
    dangerSubtle: null,
    infoSubtle: null,
  },
  font: {
    family: null,
    familyDisplay: null,
    familyMono: null,
    weight: {
      regular: null,
      medium: null,
      semibold: null,
      bold: null,
    },
    size: {
      xs: null,
      sm: null,
      md: null,
      lg: null,
      xl: null,
      display: null,
    },
    lineHeight: {
      tight: null,
      normal: null,
      relaxed: null,
    },
    letterSpacing: {
      tight: null,
      normal: null,
    },
  },
  space: {
    1: null,
    2: null,
    3: null,
    4: null,
    6: null,
    8: null,
    10: null,
    12: null,
  },
  radius: {
    sm: null,
    md: null,
    lg: null,
    full: null,
  },
  shadow: {
    sm: null,
    md: null,
  },
  transition: {
    fast: null,
  },
  height: {
    gnb: null,
  },
  width: {
    navigation: null,
  },
}, (_value, path) => path.join("-").replace(/^space-/, "spacing-"));

createGlobalTheme(":root", vars, {
  color: {
    canvas: "#f4f4f3",
    surface: "#ffffff",
    surfaceSubtle: "#f7f7f6",
    border: "#e5e5e3",
    borderPrimary: "#d1d1ce",
    textPrimary: "#171717",
    textSecondary: "#737373",
    textInverse: "#ffffff",
    navigation: "#171717",
    navigationSurface: "#202020",
    navigationBorder: "#303030",
    navigationText: "#d4d4d4",
    navigationTextSecondary: "#8b8b8b",
    navigationAccent: "#3ecf8e",
    brand: "#1f8a5b",
    brandHover: "#187149",
    success: "#1f8a5b",
    successSubtle: "#e8f8f0",
    warning: "#a15c00",
    warningSubtle: "#fff4da",
    danger: "#b42318",
    dangerSubtle: "#fdecec",
    infoSubtle: "#e8f8f0",
  },
  font: {
    family:
      "var(--font-inter), Pretendard, Apple SD Gothic Neo, system-ui, sans-serif",
    familyDisplay:
      "var(--font-inter), Pretendard, Apple SD Gothic Neo, system-ui, sans-serif",
    familyMono: "SFMono-Regular, Consolas, Liberation Mono, monospace",
    weight: {
      regular: "400",
      medium: "500",
      semibold: "600",
      bold: "700",
    },
    size: {
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.25rem",
      xl: "1.5rem",
      display: "2.5rem",
    },
    lineHeight: {
      tight: "1.2",
      normal: "1.5",
      relaxed: "1.7",
    },
    letterSpacing: {
      tight: "-0.02em",
      normal: "0",
    },
  },
  space: {
    1: "0.25rem",
    2: "0.5rem",
    3: "0.75rem",
    4: "1rem",
    6: "1.5rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
  },
  radius: {
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    full: "999px",
  },
  shadow: {
    sm: "0 1px 2px rgb(23 23 23 / 0.06)",
    md: "0 8px 24px rgb(23 23 23 / 0.10)",
  },
  transition: {
    fast: "160ms ease",
  },
  height: {
    gnb: "56px",
  },
  width: {
    navigation: "248px",
  },
});
