alter table projects add column key text;

with numbered_projects as (
  select id, row_number() over (partition by workspace_id order by created_at, id) as position
  from projects
)
update projects
set key = 'PRJ' || numbered_projects.position
from numbered_projects
where projects.id = numbered_projects.id;

alter table projects
  alter column key set not null,
  add constraint projects_workspace_key_unique unique (workspace_id, key),
  add constraint projects_key_format_check check (key ~ '^[A-Z][A-Z0-9]{1,9}$');

alter table issues
  add column number bigint generated by default as identity,
  add column due_at date,
  add constraint issues_project_number_unique unique (project_id, number);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.users (id, email, name)
  values (
    new.id,
    new.email,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

create or replace function public.create_workspace_with_project(
  workspace_name text,
  workspace_slug text,
  project_name text,
  project_key text
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  created_workspace_id uuid;
begin
  insert into public.workspaces (name, slug, owner_id)
  values (workspace_name, workspace_slug, auth.uid())
  returning id into created_workspace_id;

  insert into public.workspace_members (workspace_id, user_id, role)
  values (created_workspace_id, auth.uid(), 'OWNER');

  insert into public.projects (workspace_id, name, key)
  values (created_workspace_id, project_name, project_key);

  return created_workspace_id;
end;
$$;

grant execute on function public.create_workspace_with_project(text, text, text, text)
  to authenticated;
